name: Build and deploy docs

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: pages-deploy
  cancel-in-progress: true

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Check out source
        uses: actions/checkout@v4

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Build site
        run: mkdocs build --site-dir /home/pmabry/infrastructure/mkdocs-site/site/
